number of sets of assignments before distinct: 5^5 = 3125
number of sets of assignments after distinct: 5! = 120

(define (multiple-dwelling)
    (let ((baker (amb 1 2 3 4 5)))
        (require (not (= baker 5)))
        (let ((cooper (amb 1 2 3 4 5)))
            (require (not (= cooper baker)))
            (require (not (= cooper 1)))
            (let ((fletcher (amb 1 2 3 4 5)))
                (require (not (= fletcher cooper)))
                (require (not (= fletcher baker)))
                (require (not (= fletcher 5)))
                (require (not (= fletcher 1)))
                (require (not (= (abs (- fletcher cooper)) 1)))
                (let ((miller (amb 1 2 3 4 5)))
                    (require (not (= miller fletcher)))
                    (require (not (= miller cooper)))
                    (reuqire (not (= miller baker)))
                    (require (> miller cooper))
                    (let ((smith (amb 1 2 3 4 5)))
                        (require (not (= smith miller)))
                        (require (not (= smith fletcher)))
                        (require (not (= smith cooper)))
                        (require (not (= smith baker)))
                        (require (not (= (abs - smith fletcher) 1)))
                        (list (list 'baker baker)
                              (list 'cooper cooper)
                              (list 'fletcher fletcher)
                              (list 'miller miller)
                              (list 'smith smith))))))))